Translations#116 -Add[Filipino]
mdolr/survol pull request #118
Opened 2020-10-13 02:39 UTC by vapx

2020-10-13 07:06 UTC, mdolr requested changes
Hey, thank you, I think you forgot to translate "Dark mode" at the end of the file, could you do it please

2020-10-14 05:31 UTC, vapx commented
@mdolr we don't have proper translation for dark mode in our language so we have to borrow english word for that :))

2020-10-14 12:00 UTC, mdolr approved these changes

2020-10-14 12:00 UTC, mdolr commented
Ok then thank you for your contribution :+1:

2020-10-14 12:00 UTC, merged