Feature: Added reddit posts integration
mdolr/survol pull request #14
Opened 2019-10-07 01:06 UTC by joshuatz

This PR is to implement the reddit-posts feature, requested in Issue #4.

Summary of changes:
 - Uses embedly as the embed generator
 - Updated link type checker to recognize (Reddit) comments vs post
 - Updated test.html with Reddit post example
 - Added `embedly-loader.js` to load the embedly code
 - Udated manifest.json to inject embedly-loader.js
 - Updated CSS to properly hide and unhide new reddit post embed

I also have some additional notes to share that might help out with future integrations:

# CSS
I had to modify your CSS to use `display:none` to hide the iframes that are created by the embed code. The problem with `visibility: hidden`, is that it can easily be overridden by children if they have `visibility: visible` (which reddit embeds do). Setting display none on the parent, however, will hide the parent and all its children, no matter what their settings are. See [this S/O question](https://stackoverflow.com/questions/5188431/parent-hidden-but-children-still-visible-i-dont-want-them-visible) for details.

# Embedly
The main way that Reddit supports embeds is through Embedly. However, Embedly also [supports hundreds of other sources](https://embed.ly/providers) other than Reddit, so you might want to evaluate using it for more of your planned integrations.

For example, for [Issue #1 - Twitter integration](https://github.com/mdolr/survol/issues/1), you could easily use Embedly for this by just slightly tweaking the reddit-post code.

## Embedly vs reddit embed
These are actually one and the same. [Reddit is an Embedly partner](https://embed.ly/stories/reddit), and if you actually do a file diff between [https://cdn.embedly.com/widgets/platform.js](https://cdn.embedly.com/widgets/platform.js) and [https://embed.redditmedia.com/widgets/platform.js](https://embed.redditmedia.com/widgets/platform.js), you can see that they are identical.

## Manually creating card code
[Here](https://embed.ly/code) is their embed generator.

## Initialization
Since the embedly code uses mutation observers, you don't actually need to call any init methods, even when you are injecting new cards into the page. However, they do have a [JS API](https://docs.embed.ly/docs/cards#javascript) if you need to explicitly generate cards.

## Direct API
I also want to point out that Reddit actually has a public oEmbed API, that would be useful if you didn't like Embedly's styling and wanted to construct your own cards. The URL is `https://www.reddit.com/oembed?url={reddit_post_or_comment_link}`

2019-10-07 14:24 UTC, hisakiyo submitted a review, later dismissed

2019-10-07 15:25 UTC, mdolr requested changes
Hello, thanks for your contribution.

I had never heard of embedly before and it seems to be a good solution in order to simplify the embedding process. 
I've seen they had pricing and ratelimiting but I assume it doesn't apply to the client-side from what I understand ? (They do not support tweets though and they basically just use the page metadata which is something I wanted to do since the beginning and that we could implement manually)

I'm requesting changes for 2 reasons :
- I already thought of changing to `display:none` in the CSS but it changed the positionning and I couldn't get it to position the same way it is positionned in the current state. (does the same with your PR -> embed should be under the link)

- Using the embedly-loader like that means the script tries to inject something on its own and it will not work (on page that do not support embedly ex: [links of this gist](https://gist.github.com/mdolr/dcac4a37d838fe28ed17ef05d229b1e6)). I tried to add `platform.js` directly to the /utils folder but it didn't work either because it tries to pull resources from the CDN.

2019-10-07 23:14 UTC, joshuatz commented
@mdolr  Thanks for the feedback. Couple things right away:

Embedly:
 - Cards are part of Embedly's free plan, and are not rate-limited, but come with branding (see the twitter demo below). [Details here](https://embed.ly/cards).
 - Embedly does support twitter - in fact, since I could re-use most of the same reddit code, I hacked together a demo in a couple of minutes. Branch is [here](https://github.com/joshuatz/survol/tree/twitter-posts), and here is a demo GIF:
![Twitter-post-POC](https://user-images.githubusercontent.com/17817563/66355450-35a6f100-e91c-11e9-84d9-816752157173.gif)

CSS:
- The problem with the `visibility` CSS is two-fold. It takes up space even when the content is hidden, and simply does not work if children inside it override it.
    - [empty space demo](https://jsfiddle.net/joshuatz/ngkm7yqa/)
    - [Children issue demo](https://jsfiddle.net/joshuatz/cr3xyqft/)
- I've added an additional commit that still uses `display: none`, but puts the tooltip back in the correct position like you wanted. I would highly recommend using this over visibility, or else you are very likely to end up with future issues.
---
I'll still make an attempt at avoiding the use of Embedly and manually using `fetch()` to hit the Reddit API - probably tomorrow. I'll ping this thread again when I have an update.

2019-10-08 05:30 UTC, mdolr commented
If you find a solution for the positionning I’ll switch to ˋdisplay: none` don’t worry, I understand the benefits from switching but it wasn’t my main priority.

The problem with the twitter integration is kind of the same problem that embedly has, the twitter embed script tries to pull other scripts from a CDN, what I was suggesting with embedly is maybe we could try to modify `platform.js` by downloading everything that it refers to from the CDN to make it work locally, or maybe we could try and use the manifest Content Security Policy (I couldn’t get it to work with twitter but I don’t really know how it works either)

I’ve posted [a question](https://twittercommunity.com/t/twitter-widget-not-working-as-content-script/130526) on the twitter dev forum to know how to inject their script as a content script but if we find a way to make embedly work we can use it while finding a better solution.

Finally thanks for all the time you’re putting into this it is really appreciated to have such contributions

2019-10-08 10:33 UTC, mdolr submitted a review, later dismissed
CSS working great! Will change to `display:none;`

Edit: found [a problem](https://i.imgur.com/QXXnh9y.gif) with it but it's probably something easy to fix. [Reddit comment where this happens](https://old.reddit.com/r/GlobalOffensive/comments/cu2ksm/headtohead_win_percentage_starladder_major_2019/exrw14j/)

2019-10-09 06:54 UTC, joshuatz commented
@mdolr OK, as requested, I just rewrote my code to use a manually crafted embed, rather than the Embedly code. It doesn't look quite as nice, since it's using my hastily written CSS rather than Embedly's team of designers (😬), but it gets the job done.

![reddit-post-integration-manual](https://user-images.githubusercontent.com/17817563/66458077-ac301580-ea26-11e9-80b0-995932de855c.gif)

Essentially, the new code manually crafts a GET request to the Reddit API (`https://api.reddit.com/api/info/`), parses the response, and generates an embed to place in the tooltip. I added a new CSS template to format this embed, and also backed out  / removed the Embedly code.

If you want to put the Embedly code back at some point, all the commit history is still there, so you could easily revert back.

Hope this is what you were looking for!

2019-10-09 20:27 UTC, mdolr commented
I've tried your changes and I'm having issues with CORS, you were right, since Q1 2019 CORS are a thing with content scripts [see chromium security post](https://www.chromium.org/Home/chromium-security/extension-content-script-fetches).

I'll try to implement the request through a background script and merge your PR when I've the time.
I still haven't given up on the embedly thing I think it is a great solution but we need to find a way to make it work everywhere and not just locally.

2019-10-09 20:54 UTC, joshuatz commented
@mdolr Sounds good, and that is interesting about the change to CORS.

Good luck on building this out more. Seems like a fun and useful extension idea!

2019-10-10 19:12 UTC, mdolr approved these changes

2019-10-10 19:20 UTC, merged