Add GitHub profile
mdolr/survol pull request #145
Opened 2020-10-20 03:37 UTC by joelazwar

Feature request #108 Adds display template for github profiles

2020-10-21 18:02 UTC, mdolr requested changes
Thank you, great pull request, could you just :
* Make the picture rounded (`border-radius:50%`)
* Display links below the repo / followers / following count
* Replace icon by text (e.g: "Twitter:", "Workplace:" (we will decide on an icon set later)

2020-10-22 01:52 UTC, joelazwar commented
@mdolr I made the changes as you requested and a few others

- Profile picture is now round
- Links are displayed below the repo/follower/following count, and i've aligned the counts to be centered as per container
- Replaced the icons for links with text for now, added some styling edits as well (e.g for unavailable links)

2020-10-23 21:44 UTC, mdolr approved these changes

2020-10-23 21:44 UTC, mdolr commented
Merged :+1:

2020-10-23 21:44 UTC, merged