Add a template for soundcloud links
mdolr/survol pull request #56
Opened 2020-10-05 09:58 UTC by VeikkoLehmuskorpi

This fixes #51 

Adds a template for SoundCloud track links, similarly to the already active YouTube video links
[Preview](https://i.imgur.com/BEmMGJq.png)

SoundCloud track links aren't distinguishable from other SoundCloud pages, they just follow an author and a title pattern. That's why the redirect link check is implemented with a regex as opposed to just checking for certain keywords like with the other template implementations.

2020-10-05 17:38 UTC, mdolr requested changes
:ok_hand: 
Works really well, if you could just get even with the master branch (`js/core.js`) so I can merge it would be perfect.

2020-10-06 04:35 UTC, VeikkoLehmuskorpi commented
Branch is now even with the master branch

2020-10-06 10:17 UTC, mdolr approved these changes

2020-10-06 10:18 UTC, mdolr commented
Perfect thank you :+1:

2020-10-06 10:18 UTC, merged